# Generated by Django 2.0.4 on 2018-05-06 22:56

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canvasser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CanvasArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvasser.Canvas')),
            ],
        ),
        migrations.CreateModel(
            name='CanvasSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('canvas_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvasser.CanvasArea')),
            ],
        ),
        migrations.CreateModel(
            name='Canvasser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='canvassector',
            name='canvassers',
            field=models.ManyToManyField(to='canvasser.Canvasser'),
        ),
        migrations.AddField(
            model_name='canvas',
            name='canvassers',
            field=models.ManyToManyField(to='canvasser.Canvasser'),
        ),
        migrations.AddField(
            model_name='canvas',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
