# Generated by Django 2.0.4 on 2018-05-19 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turfcutter', '0005_auto_20180519_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='turfcutter.Campaign'),
            preserve_default=False,
        ),
    ]
