# Generated by Django 2.0.4 on 2018-05-19 17:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turfcutter', '0007_auto_20180519_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_home', models.BooleanField()),
                ('response', models.SmallIntegerField()),
                ('campaign_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('canvas', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='turfcutter.Canvas')),
                ('canvassers', models.ManyToManyField(blank=True, to='turfcutter.Canvasser')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140, null=True)),
                ('parcel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='turfcutter.Parcel')),
            ],
        ),
        migrations.AddField(
            model_name='interaction',
            name='unit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='turfcutter.Unit'),
        ),
    ]
