# Generated by Django 2.0.5 on 2018-05-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfcutter', '0008_auto_20180519_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='name',
            field=models.CharField(default='unnamed', max_length=140),
            preserve_default=False,
        ),
    ]
