# Generated by Django 2.0.5 on 2018-05-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfcutter', '0009_turf_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='canvassers',
            field=models.ManyToManyField(blank=True, to='turfcutter.Canvasser'),
        ),
    ]
