# Generated by Django 2.0.5 on 2018-05-30 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turfcutter', '0010_auto_20180530_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='parcel',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='canvas',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='canvassers',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='response',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='unit',
        ),
        migrations.AddField(
            model_name='interaction',
            name='accepted_material',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='interaction',
            name='campaign_response',
            field=models.SmallIntegerField(choices=[(1, 'NEGATIVE'), (2, 'NEUTRAL'), (3, 'POSITIVE')], default=2),
        ),
        migrations.AddField(
            model_name='interaction',
            name='dsa_response',
            field=models.SmallIntegerField(choices=[(1, 'NEGATIVE'), (2, 'NEUTRAL'), (3, 'POSITIVE')], default=2),
        ),
        migrations.AddField(
            model_name='interaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='parcel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='turfcutter.Parcel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interaction',
            name='turf',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='turfcutter.Turf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interaction',
            name='at_home',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
