# Generated by Django 2.0.6 on 2018-06-28 00:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turfcutter', '0012_auto_20180530_0444'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Canvas',
            new_name='Canvass',
        ),
        migrations.RenameModel(
            old_name='CanvasArea',
            new_name='CanvassArea',
        ),
        migrations.RenameField(
            model_name='canvassarea',
            old_name='canvas',
            new_name='canvass',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='canvas',
            new_name='canvass',
        ),
    ]
