# Generated by Django 2.0.6 on 2018-07-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfcutter', '0017_auto_20180705_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voterid',
            field=models.BigIntegerField(),
        ),
    ]
